FROM node:22-alpine AS base
WORKDIR /app

COPY apps/web/package.json ./

FROM base AS deps
RUN npm install

FROM base AS build
COPY --from=deps /app/node_modules ./node_modules
COPY apps/web ./
RUN rm -rf .next
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=deps /app/node_modules ./node_modules
EXPOSE 3000
CMD ["npm", "run", "start"]
