/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiForthsoftWebhookRouteImport } from './routes/api/forthsoft-webhook'
import { Route as AuthedWisdomdropRouteImport } from './routes/_authed/wisdomdrop'
import { Route as AuthedWinnersRouteImport } from './routes/_authed/winners'
import { Route as AuthedResultsRouteImport } from './routes/_authed/results'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedEntriesRouteImport } from './routes/_authed/entries'
import { Route as AuthedCheckmateRouteImport } from './routes/_authed/checkmate'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForthsoftWebhookRoute = ApiForthsoftWebhookRouteImport.update({
  id: '/api/forthsoft-webhook',
  path: '/api/forthsoft-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWisdomdropRoute = AuthedWisdomdropRouteImport.update({
  id: '/wisdomdrop',
  path: '/wisdomdrop',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWinnersRoute = AuthedWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResultsRoute = AuthedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEntriesRoute = AuthedEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckmateRoute = AuthedCheckmateRouteImport.update({
  id: '/checkmate',
  path: '/checkmate',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/app': typeof AuthedAppRoute
  '/checkmate': typeof AuthedCheckmateRoute
  '/entries': typeof AuthedEntriesRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/results': typeof AuthedResultsRoute
  '/winners': typeof AuthedWinnersRoute
  '/wisdomdrop': typeof AuthedWisdomdropRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/app': typeof AuthedAppRoute
  '/checkmate': typeof AuthedCheckmateRoute
  '/entries': typeof AuthedEntriesRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/results': typeof AuthedResultsRoute
  '/winners': typeof AuthedWinnersRoute
  '/wisdomdrop': typeof AuthedWisdomdropRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/checkmate': typeof AuthedCheckmateRoute
  '/_authed/entries': typeof AuthedEntriesRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/results': typeof AuthedResultsRoute
  '/_authed/winners': typeof AuthedWinnersRoute
  '/_authed/wisdomdrop': typeof AuthedWisdomdropRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/app'
    | '/checkmate'
    | '/entries'
    | '/leaderboard'
    | '/profile'
    | '/results'
    | '/winners'
    | '/wisdomdrop'
    | '/api/forthsoft-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/app'
    | '/checkmate'
    | '/entries'
    | '/leaderboard'
    | '/profile'
    | '/results'
    | '/winners'
    | '/wisdomdrop'
    | '/api/forthsoft-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/_authed/app'
    | '/_authed/checkmate'
    | '/_authed/entries'
    | '/_authed/leaderboard'
    | '/_authed/profile'
    | '/_authed/results'
    | '/_authed/winners'
    | '/_authed/wisdomdrop'
    | '/api/forthsoft-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RenewRoute: typeof RenewRoute
  SubscribeRoute: typeof SubscribeRoute
  VerifyRoute: typeof VerifyRoute
  ApiForthsoftWebhookRoute: typeof ApiForthsoftWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forthsoft-webhook': {
      id: '/api/forthsoft-webhook'
      path: '/api/forthsoft-webhook'
      fullPath: '/api/forthsoft-webhook'
      preLoaderRoute: typeof ApiForthsoftWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/wisdomdrop': {
      id: '/_authed/wisdomdrop'
      path: '/wisdomdrop'
      fullPath: '/wisdomdrop'
      preLoaderRoute: typeof AuthedWisdomdropRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/winners': {
      id: '/_authed/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof AuthedWinnersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/results': {
      id: '/_authed/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthedResultsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/entries': {
      id: '/_authed/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof AuthedEntriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkmate': {
      id: '/_authed/checkmate'
      path: '/checkmate'
      fullPath: '/checkmate'
      preLoaderRoute: typeof AuthedCheckmateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedCheckmateRoute: typeof AuthedCheckmateRoute
  AuthedEntriesRoute: typeof AuthedEntriesRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedResultsRoute: typeof AuthedResultsRoute
  AuthedWinnersRoute: typeof AuthedWinnersRoute
  AuthedWisdomdropRoute: typeof AuthedWisdomdropRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedCheckmateRoute: AuthedCheckmateRoute,
  AuthedEntriesRoute: AuthedEntriesRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedResultsRoute: AuthedResultsRoute,
  AuthedWinnersRoute: AuthedWinnersRoute,
  AuthedWisdomdropRoute: AuthedWisdomdropRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RenewRoute: RenewRoute,
  SubscribeRoute: SubscribeRoute,
  VerifyRoute: VerifyRoute,
  ApiForthsoftWebhookRoute: ApiForthsoftWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
