/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiForthsoftWebhookRouteImport } from './routes/api/forthsoft-webhook'
import { Route as AdminWinnersRouteImport } from './routes/admin.winners'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminMissionsRouteImport } from './routes/admin.missions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminDrawRouteImport } from './routes/admin.draw'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AuthedWisdomdropRouteImport } from './routes/_authed/wisdomdrop'
import { Route as AuthedWinnersRouteImport } from './routes/_authed/winners'
import { Route as AuthedResultsRouteImport } from './routes/_authed/results'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedKycRouteImport } from './routes/_authed/kyc'
import { Route as AuthedEntriesRouteImport } from './routes/_authed/entries'
import { Route as AuthedCheckmateRouteImport } from './routes/_authed/checkmate'
import { Route as AuthedAppRouteImport } from './routes/_authed/app'
import { Route as AdminPlayersPlayerIdRouteImport } from './routes/admin.players.$playerId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiForthsoftWebhookRoute = ApiForthsoftWebhookRouteImport.update({
  id: '/api/forthsoft-webhook',
  path: '/api/forthsoft-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMissionsRoute = AdminMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDrawRoute = AdminDrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedWisdomdropRoute = AuthedWisdomdropRouteImport.update({
  id: '/wisdomdrop',
  path: '/wisdomdrop',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWinnersRoute = AuthedWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResultsRoute = AuthedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedKycRoute = AuthedKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEntriesRoute = AuthedEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckmateRoute = AuthedCheckmateRouteImport.update({
  id: '/checkmate',
  path: '/checkmate',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthedRoute,
} as any)
const AdminPlayersPlayerIdRoute = AdminPlayersPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => AdminPlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/app': typeof AuthedAppRoute
  '/checkmate': typeof AuthedCheckmateRoute
  '/entries': typeof AuthedEntriesRoute
  '/kyc': typeof AuthedKycRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/results': typeof AuthedResultsRoute
  '/winners': typeof AuthedWinnersRoute
  '/wisdomdrop': typeof AuthedWisdomdropRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/draw': typeof AdminDrawRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/winners': typeof AdminWinnersRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/players/$playerId': typeof AdminPlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/app': typeof AuthedAppRoute
  '/checkmate': typeof AuthedCheckmateRoute
  '/entries': typeof AuthedEntriesRoute
  '/kyc': typeof AuthedKycRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/profile': typeof AuthedProfileRoute
  '/results': typeof AuthedResultsRoute
  '/winners': typeof AuthedWinnersRoute
  '/wisdomdrop': typeof AuthedWisdomdropRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/draw': typeof AdminDrawRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/winners': typeof AdminWinnersRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
  '/admin': typeof AdminIndexRoute
  '/admin/players/$playerId': typeof AdminPlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/renew': typeof RenewRoute
  '/subscribe': typeof SubscribeRoute
  '/verify': typeof VerifyRoute
  '/_authed/app': typeof AuthedAppRoute
  '/_authed/checkmate': typeof AuthedCheckmateRoute
  '/_authed/entries': typeof AuthedEntriesRoute
  '/_authed/kyc': typeof AuthedKycRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/results': typeof AuthedResultsRoute
  '/_authed/winners': typeof AuthedWinnersRoute
  '/_authed/wisdomdrop': typeof AuthedWisdomdropRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/draw': typeof AdminDrawRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/missions': typeof AdminMissionsRoute
  '/admin/players': typeof AdminPlayersRouteWithChildren
  '/admin/winners': typeof AdminWinnersRoute
  '/api/forthsoft-webhook': typeof ApiForthsoftWebhookRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/players/$playerId': typeof AdminPlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/app'
    | '/checkmate'
    | '/entries'
    | '/kyc'
    | '/leaderboard'
    | '/profile'
    | '/results'
    | '/winners'
    | '/wisdomdrop'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/draw'
    | '/admin/help'
    | '/admin/login'
    | '/admin/missions'
    | '/admin/players'
    | '/admin/winners'
    | '/api/forthsoft-webhook'
    | '/admin/'
    | '/admin/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/app'
    | '/checkmate'
    | '/entries'
    | '/kyc'
    | '/leaderboard'
    | '/profile'
    | '/results'
    | '/winners'
    | '/wisdomdrop'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/draw'
    | '/admin/help'
    | '/admin/login'
    | '/admin/missions'
    | '/admin/players'
    | '/admin/winners'
    | '/api/forthsoft-webhook'
    | '/admin'
    | '/admin/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/renew'
    | '/subscribe'
    | '/verify'
    | '/_authed/app'
    | '/_authed/checkmate'
    | '/_authed/entries'
    | '/_authed/kyc'
    | '/_authed/leaderboard'
    | '/_authed/profile'
    | '/_authed/results'
    | '/_authed/winners'
    | '/_authed/wisdomdrop'
    | '/admin/banners'
    | '/admin/config'
    | '/admin/draw'
    | '/admin/help'
    | '/admin/login'
    | '/admin/missions'
    | '/admin/players'
    | '/admin/winners'
    | '/api/forthsoft-webhook'
    | '/admin/'
    | '/admin/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RenewRoute: typeof RenewRoute
  SubscribeRoute: typeof SubscribeRoute
  VerifyRoute: typeof VerifyRoute
  ApiForthsoftWebhookRoute: typeof ApiForthsoftWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/forthsoft-webhook': {
      id: '/api/forthsoft-webhook'
      path: '/api/forthsoft-webhook'
      fullPath: '/api/forthsoft-webhook'
      preLoaderRoute: typeof ApiForthsoftWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/missions': {
      id: '/admin/missions'
      path: '/missions'
      fullPath: '/admin/missions'
      preLoaderRoute: typeof AdminMissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/draw': {
      id: '/admin/draw'
      path: '/draw'
      fullPath: '/admin/draw'
      preLoaderRoute: typeof AdminDrawRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/wisdomdrop': {
      id: '/_authed/wisdomdrop'
      path: '/wisdomdrop'
      fullPath: '/wisdomdrop'
      preLoaderRoute: typeof AuthedWisdomdropRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/winners': {
      id: '/_authed/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof AuthedWinnersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/results': {
      id: '/_authed/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthedResultsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/kyc': {
      id: '/_authed/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AuthedKycRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/entries': {
      id: '/_authed/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof AuthedEntriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkmate': {
      id: '/_authed/checkmate'
      path: '/checkmate'
      fullPath: '/checkmate'
      preLoaderRoute: typeof AuthedCheckmateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app': {
      id: '/_authed/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/admin/players/$playerId': {
      id: '/admin/players/$playerId'
      path: '/$playerId'
      fullPath: '/admin/players/$playerId'
      preLoaderRoute: typeof AdminPlayersPlayerIdRouteImport
      parentRoute: typeof AdminPlayersRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAppRoute: typeof AuthedAppRoute
  AuthedCheckmateRoute: typeof AuthedCheckmateRoute
  AuthedEntriesRoute: typeof AuthedEntriesRoute
  AuthedKycRoute: typeof AuthedKycRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedResultsRoute: typeof AuthedResultsRoute
  AuthedWinnersRoute: typeof AuthedWinnersRoute
  AuthedWisdomdropRoute: typeof AuthedWisdomdropRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAppRoute: AuthedAppRoute,
  AuthedCheckmateRoute: AuthedCheckmateRoute,
  AuthedEntriesRoute: AuthedEntriesRoute,
  AuthedKycRoute: AuthedKycRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedResultsRoute: AuthedResultsRoute,
  AuthedWinnersRoute: AuthedWinnersRoute,
  AuthedWisdomdropRoute: AuthedWisdomdropRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminPlayersRouteChildren {
  AdminPlayersPlayerIdRoute: typeof AdminPlayersPlayerIdRoute
}

const AdminPlayersRouteChildren: AdminPlayersRouteChildren = {
  AdminPlayersPlayerIdRoute: AdminPlayersPlayerIdRoute,
}

const AdminPlayersRouteWithChildren = AdminPlayersRoute._addFileChildren(
  AdminPlayersRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminDrawRoute: typeof AdminDrawRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMissionsRoute: typeof AdminMissionsRoute
  AdminPlayersRoute: typeof AdminPlayersRouteWithChildren
  AdminWinnersRoute: typeof AdminWinnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminDrawRoute: AdminDrawRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMissionsRoute: AdminMissionsRoute,
  AdminPlayersRoute: AdminPlayersRouteWithChildren,
  AdminWinnersRoute: AdminWinnersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RenewRoute: RenewRoute,
  SubscribeRoute: SubscribeRoute,
  VerifyRoute: VerifyRoute,
  ApiForthsoftWebhookRoute: ApiForthsoftWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
